USE [master]
GO
/****** Object:  Database [PuntoVenta]    Script Date: 08/09/2018 09:55:56 a. m. ******/
CREATE DATABASE [PuntoVenta]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PuntoVenta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\PuntoVenta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PuntoVenta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\PuntoVenta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [PuntoVenta] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PuntoVenta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PuntoVenta] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PuntoVenta] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PuntoVenta] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PuntoVenta] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PuntoVenta] SET ARITHABORT OFF 
GO
ALTER DATABASE [PuntoVenta] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PuntoVenta] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PuntoVenta] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PuntoVenta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PuntoVenta] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PuntoVenta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PuntoVenta] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PuntoVenta] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PuntoVenta] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PuntoVenta] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PuntoVenta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PuntoVenta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PuntoVenta] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PuntoVenta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PuntoVenta] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PuntoVenta] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PuntoVenta] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PuntoVenta] SET RECOVERY FULL 
GO
ALTER DATABASE [PuntoVenta] SET  MULTI_USER 
GO
ALTER DATABASE [PuntoVenta] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PuntoVenta] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PuntoVenta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PuntoVenta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PuntoVenta] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'PuntoVenta', N'ON'
GO
ALTER DATABASE [PuntoVenta] SET QUERY_STORE = OFF
GO
USE [PuntoVenta]
GO
/****** Object:  Table [dbo].[Cajero]    Script Date: 08/09/2018 09:55:57 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cajero](
	[ID_Cajero] [int] NOT NULL,
	[Nombre_Cajero] [varchar](30) NOT NULL,
	[Turno_Cajero] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Cajero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 08/09/2018 09:55:58 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[ID_Cliente] [int] NOT NULL,
	[Registrado] [bit] NOT NULL,
	[Telefono_Cliente] [varchar](14) NULL,
	[Correo_Cliente] [varchar](40) NULL,
	[Num_Visitas] [tinyint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NotaDeVenta]    Script Date: 08/09/2018 09:55:58 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NotaDeVenta](
	[ID_Venta] [int] IDENTITY(1,1) NOT NULL,
	[ID_Cliente] [int] NOT NULL,
	[Cant_Producto] [int] NOT NULL,
	[ID_Producto] [int] NOT NULL,
	[Fecha_Venta] [date] NOT NULL,
	[ID_Cajero] [int] NOT NULL,
	[Total_Venta] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Venta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pago]    Script Date: 08/09/2018 09:55:58 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pago](
	[ID_Pago] [int] NOT NULL,
	[Forma_Pago] [varchar](20) NOT NULL,
	[Total_Pago] [float] NOT NULL,
	[Notas] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Pago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 08/09/2018 09:55:58 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[ID_Producto] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion_Producto] [varchar](50) NOT NULL,
	[Precio_Venta] [float] NOT NULL,
	[Descuento] [float] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_Producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NotaDeVenta]  WITH CHECK ADD FOREIGN KEY([ID_Cajero])
REFERENCES [dbo].[Cajero] ([ID_Cajero])
GO
ALTER TABLE [dbo].[NotaDeVenta]  WITH CHECK ADD FOREIGN KEY([ID_Cliente])
REFERENCES [dbo].[Cliente] ([ID_Cliente])
GO
ALTER TABLE [dbo].[NotaDeVenta]  WITH CHECK ADD FOREIGN KEY([ID_Producto])
REFERENCES [dbo].[Producto] ([ID_Producto])
GO
USE [master]
GO
ALTER DATABASE [PuntoVenta] SET  READ_WRITE 
GO
